package ctec.p3compendium.controller;

import android.app.Activity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;

public class CharScreen extends Activity
{

	private int [][] stats;
	private String[] charName;
	private String charType;
	
	@Override
	protected void onCreate(Bundle savedInstanceState)
	{
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_char_screen);
		charType = getIntent().getExtras().getString("type");
		
		charName = new String[]
				
				{
					"Orpheus",
					"Slime",
					"Legion",
					"Ose",
					"Black Frost",
					"Decarabia",
					"Loki",
					"Susano-o",
					"Orpheus Telos",
					"Nekomata",
					"Jack Frost",
					"Pyro Jack",
					"Hua Po",
					"Sati",
					"Orobas",
					"Rangda",
					"Surt",
					"Apsaras",
					"Unicorn",
					"High Pixie",
					"Sarasvati",
					"Ganga",
					"Parvati",
					"Kikuri-hime",
					"Scathach",
					"Leanan Sidhe",
					"Yaksini",
					"Laksmi",
					"Hariti",
					"Gabriel",
					"Mother Harlot",
					"Skadi",
					"Alilat",
					"Forneus",
					"Oberon",
					"Take-Mikazuchi",
					"King Frost",
					"Raja Naga",
					"Kingu",
					"Barong",
					"Odin",
					"Omoikane",
					"Berith",
					"Shiisaa",
					"Flauros",
					"Thoth",
					"Hokuto Seikun",
					"Daisoujou",
					"Kohryu",
					"Pixie",
					"Alp",
					"Narcissus",
					"Queen Mab",
					"Saki Mitama",
					"Titania",
					"Raphael",
					"Cybele",
					"Ara Mitama",
					"Chimera",
					"Zouchouten",
					"Ares",
					"Oumitsunu",
					"Nata Taishi",
					"Koumokuten",
					"Thor",
					"Amgel",
					"Archangel",
					"Principlaity",
					"Power",
					"Virtue",
					"Dominion",
					"Throne",
					"Melchizedek",
					"Yomotsu-Shikome",
					"Naga",
					"Lamia",
					"Mothman",
					"Taraka",
					"Kurama Tengu",
					"Nebrios",
					"Kumbhanda",
					"Arahabaki",
					"Fortuna",
					"Empus",
					"Kusi Mitama",
					"Clotho",
					"Lachesis",
					"Atropos",
					"Norn",
					"Cerberus",
					"Valkyrie",
					"Rakshasa",
					"Titan",
					"Jikoukuten",
					"Hanuman",
					"Narashima",
					"Kali",
					"Siegfried",
					"Inugami",
					"Taka-Minakata",
					"Orthrus",
					"Vasuki",
					"Ubelluris",
					"Hecatoncheires",
					"Hell Biker",
					"Attis",
					"Ghoul",
					"Pale Rider",
					"Loa",
					"Samael",
					"Mot",
					"Alice",
					"Thanatos",
					"Nigi Mitama",
					"Mithra",
					"Genbu",
					"Seiryuu",
					"Okuninushi",
					"Suzaku",
					"Byakko",
					"Yurlungur",
					"Lilim",
					"Vetala",
					"Incubus",
					"Succubus",
					"Pazuzu",
					"Lilith",
					"Abaddon",
					"Beelzebub",
					"Eligor",
					"Chu Chulainn",
					"Bishamonten",
					"Seiten Taisei",
					"Masakado",
					"Mara",
					"Shiva",
					"Chi You",
					"Nandi",
					"Kaiwan",
					"Ganesha",
					"Garuda",
					"Kartikeya",
					"Saturnus",
					"Helel",
					"Gurr",
					"Yamata-no-Orochi",
					"Girimehkala",
					"Dionysus",
					"Chernobog",
					"Seth",
					"Baal Zebul",
					"Sandalphon",
					"Yatagarasu",
					"Quetzalcoatl",
					"Jatayu",
					"Horus",
					"Sparna",
					"Vishnu",
					"Asura",
					"Anubis",
					"Trumpeter",
					"Michael",
					"Satan",
					"Lucifer",
					"Messiah",
					"Uriel",
					"Nidhogg",
					"Ananta",
					"Atavaka",
					"Metatron",
				};
		
		stats = new int [][]
				{ 
					{1,2,2,2,2,2},
					{},
					{12,11,9,11,4,8},
					{22,20,13,15,14,11},
					{34,23,25,25,26,26},
					{44,25,35,25,26,28},
					{55,40,42,29,41,20},
					{76,57,51,53,49,53},
					{},
					{5,4,6,5,3,4},
					{8,5,8,8,4,6},
					{14,7,14,9,8,11},
					{},
					{28,17,25,18,16,15},
					{34,20,29,21,22,27},
					{40,25,35,24,22,21},
					{52,40,49,35,26,32},
					{3,3,4,3,2,4},
					{11,7,10,8,9,6},
					{},
					{27,13,23,14,20,18},
					{35,18,28,21,22,23},
					{47,24,38,25,32,33},
					{53,29,45,28,30,34},
					{64,51,53,29,49,40},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},
					{},		
				};
		//* where we initialize all the text views, pics.
		
	}
}
